In [17]:
import pandas as pd
import json

# Australia, Barossa Valley

In [30]:
# listings
listings_df = pd.read_csv("airbnb_data/20241227_australia_sa_barossa-valley_listings.csv")
listings_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,47117855,https://www.airbnb.com/rooms/47117855,20241227033100,2024-12-27,city scrape,Peaceful 2br cottage in the 🖤 of Angaston,Plum Cottage is a renovated 1940’s miner’s cot...,"The cottage is on a quiet local street, 5 minu...",https://a0.muscache.com/pictures/844ce91e-d5fa...,5100298,...,4.95,4.86,4.71,NaN,f,2,2,0,0,2.23
1,1185895451922999542,https://www.airbnb.com/rooms/1185895451922999542,20241227033100,2024-12-27,city scrape,Jacobs Creek Retreat - Orchard,"Our ""Honeymoon Suite""; this beautifully restor...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,262121622,...,NaN,NaN,NaN,NaN,f,8,1,7,0,NaN
2,611369443768980724,https://www.airbnb.com/rooms/611369443768980724,20241227033100,2024-12-27,previous scrape,Neat & Tidy Home with Outdoor Entertaining Area,51 Gramp Ave overlooks the wonderful Angas Rec...,Peaceful,https://a0.muscache.com/pictures/miso/Hosting-...,455612017,...,5.00,4.96,4.81,NaN,t,1,1,0,0,0.84
3,861068035850251868,https://www.airbnb.com/rooms/861068035850251868,20241227033100,2024-12-27,city scrape,Kaiser Ridge - eco stay Kaiser,"The pinnacle of Kaiser Ridge, this tiny house ...",NaN,https://a0.muscache.com/pictures/prohost-api/H...,329243003,...,5.00,5.00,5.00,NaN,t,3,3,0,0,1.45
4,1095252810134424371,https://www.airbnb.com/rooms/1095252810134424371,20241227033100,2024-12-27,city scrape,Benbullen Pavilion One,Welcome to Benbullen Pavilions - a stylish and...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,466461269,...,5.00,5.00,5.00,NaN,t,4,4,0,0,0.54

In [12]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354 entries, 0 to 353
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            354 non-null    int64
 1   listing_url                                   354 non-null    object
 2   scrape_id                                     354 non-null    int64
 3   last_scraped                                  354 non-null    object
 4   source                                        354 non-null    object
 5   name                                          354 non-null    object
 6   description                                   345 non-null    object
 7   neighborhood_overview                         212 non-null    object
 8   picture_url                                   354 non-null    object
 9   host_id                                       354 non-null    int64
 10  host_url                                      354 non-null    object
 11  host_name                                     354 non-null    object
 12  host_since                                    354 non-null    object
 13  host_location                                 223 non-null    object
 14  host_about                                    172 non-null    object
 15  host_response_time                            307 non-null    object
 16  host_response_rate                            307 non-null    object
 17  host_acceptance_rate                          323 non-null    object
 18  host_is_superhost                             351 non-null    object
 19  host_thumbnail_url                            354 non-null    object
 20  host_picture_url                              354 non-null    object
 21  host_neighbourhood                            0 non-null      float64
 22  host_listings_count                           354 non-null    int64
 23  host_total_listings_count                     354 non-null    int64
 24  host_verifications                            354 non-null    object
 25  host_has_profile_pic                          354 non-null    object
 26  host_identity_verified                        354 non-null    object
 27  neighbourhood                                 212 non-null    object
 28  neighbourhood_cleansed                        354 non-null    object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      354 non-null    float64
 31  longitude                                     354 non-null    float64
 32  property_type                                 354 non-null    object
 33  room_type                                     354 non-null    object
 34  accommodates                                  354 non-null    int64
 35  bathrooms                                     325 non-null    float64
 36  bathrooms_text                                354 non-null    object
 37  bedrooms                                      352 non-null    float64
 38  beds                                          325 non-null    float64
 39  amenities                                     354 non-null    object
 40  price                                         325 non-null    object
 41  minimum_nights                                354 non-null    int64
 42  maximum_nights                                354 non-null    int64
 43  minimum_minimum_nights                        354 non-null    int64
 44  maximum_minimum_nights                        354 non-null    int64
 45  minimum_maximum_nights                        354 non-null    int64
 46  maximum_maximum_nights                        354 non-null    int64
 47  minimum_nights_avg_ntm                        354 non-null    float64
 48  maximum_nights_avg_ntm                        354 non-null    float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              350 non-null    object
 51  availability_30                               354 non-null    int64
 52  availability_60                               354 non-null    int64
 53  availability_90                               354 non-null    int64
 54  availability_365                              354 non-null    int64
 55  calendar_last_scraped                         354 non-null    object
 56  number_of_reviews                             354 non-null    int64
 57  number_of_reviews_ltm                         354 non-null    int64
 58  number_of_reviews_l30d                        354 non-null    int64
 59  first_review                                  311 non-null    object
 60  last_review                                   311 non-null    object
 61  review_scores_rating                          311 non-null    float64
 62  review_scores_accuracy                        311 non-null    float64
 63  review_scores_cleanliness                     311 non-null    float64
 64  review_scores_checkin                         311 non-null    float64
 65  review_scores_communication                   311 non-null    float64
 66  review_scores_location                        311 non-null    float64
 67  review_scores_value                           311 non-null    float64
 68  license                                       0 non-null      float64
 69  instant_bookable                              354 non-null    object
 70  calculated_host_listings_count                354 non-null    int64
 71  calculated_host_listings_count_entire_homes   354 non-null    int64
 72  calculated_host_listings_count_private_rooms  354 non-null    int64
 73  calculated_host_listings_count_shared_rooms   354 non-null    int64
 74  reviews_per_month                             311 non-null    float64
dtypes: float64(19), int64(23), object(33)
memory usage: 207.6+ KB

In [32]:
print("\n".join(listings_df.columns))

id
listing_url
scrape_id
last_scraped
source
name
description
neighborhood_overview
picture_url
host_id
host_url
host_name
host_since
host_location
host_about
host_response_time
host_response_rate
host_acceptance_rate
host_is_superhost
host_thumbnail_url
host_picture_url
host_neighbourhood
host_listings_count
host_total_listings_count
host_verifications
host_has_profile_pic
host_identity_verified
neighbourhood
neighbourhood_cleansed
neighbourhood_group_cleansed
latitude
longitude
property_type
room_type
accommodates
bathrooms
bathrooms_text
bedrooms
beds
amenities
price
minimum_nights
maximum_nights
minimum_minimum_nights
maximum_minimum_nights
minimum_maximum_nights
maximum_maximum_nights
minimum_nights_avg_ntm
maximum_nights_avg_ntm
calendar_updated
has_availability
availability_30
availability_60
availability_90
availability_365
calendar_last_scraped
number_of_reviews
number_of_reviews_ltm
number_of_reviews_l30d
first_review
last_review
review_scores_rating
review_scores_accuracy
review_scores_cleanliness
review_scores_checkin
review_scores_communication
review_scores_location
review_scores_value
license
instant_bookable
calculated_host_listings_count
calculated_host_listings_count_entire_homes
calculated_host_listings_count_private_rooms
calculated_host_listings_count_shared_rooms
reviews_per_month

In [28]:
listings_df["neighbourhood_group_cleansed"]

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
349   NaN
350   NaN
351   NaN
352   NaN
353   NaN
Name: neighbourhood_group_cleansed, Length: 354, dtype: float64

In [4]:
# calendar
calendar_df = pd.read_csv("airbnb_data/20241227_australia_sa_barossa-valley_calendar.csv")
calendar_df.head()

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,1125097,2024-12-27,f,$250.00,NaN,2,14
1,1125097,2024-12-28,t,$250.00,NaN,2,14
2,1125097,2024-12-29,t,$250.00,NaN,2,14
3,1125097,2024-12-30,f,$250.00,NaN,2,14
4,1125097,2024-12-31,f,$250.00,NaN,2,14

In [10]:
calendar_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129210 entries, 0 to 129209
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   listing_id      129210 non-null  int64
 1   date            129210 non-null  object
 2   available       129210 non-null  object
 3   price           129210 non-null  object
 4   adjusted_price  0 non-null       float64
 5   minimum_nights  129210 non-null  int64
 6   maximum_nights  129210 non-null  int64
dtypes: float64(1), int64(3), object(3)
memory usage: 6.9+ MB

In [33]:
print("\n".join(calendar_df.columns))

listing_id
date
available
price
adjusted_price
minimum_nights
maximum_nights

In [8]:
# reviews
reviews_df = pd.read_csv("airbnb_data/20241227_australia_sa_barossa-valley_reviews.csv")
reviews_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,1125097,7269778,2013-09-13,3053083,Stephen,While I didnt have the pleasure of meeting Hea...
1,1125097,10081118,2014-01-29,1898281,Rus,Great host and amazing accommodation! \r<br/>...
2,1125097,10335170,2014-02-14,2725224,Teresa,"A lovely and convenient location, surrounded b..."
3,1125097,10881952,2014-03-11,8982612,Kathy,A wonderful experience from start to finish . ...
4,1125097,11872081,2014-04-17,10977428,Phillip,The coach house is in a lovely location. We we...

In [13]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20976 entries, 0 to 20975
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     20976 non-null  int64
 1   id             20976 non-null  int64
 2   date           20976 non-null  object
 3   reviewer_id    20976 non-null  int64
 4   reviewer_name  20976 non-null  object
 5   comments       20975 non-null  object
dtypes: int64(3), object(3)
memory usage: 983.4+ KB

In [34]:
print("\n".join(reviews_df.columns))

listing_id
id
date
reviewer_id
reviewer_name
comments

In [18]:
with open("airbnb_data/20241227_australia_sa_barossa-valley_neighbourhoods.geojson", "r", encoding="utf-8") as f:
    data = json.load(f)

# Pokaż klucze i przykład właściwości
print("Klucze w pliku:", data.keys())
print("Typ danych:", type(data["features"]))
print("Liczba obiektów:", len(data["features"]))

# Przykładowy pierwszy obiekt
first_feature = data["features"][0]
print("Properties:", first_feature["properties"])

Klucze w pliku: dict_keys(['type', 'features'])
Typ danych: <class 'list'>
Liczba obiektów: 33
Properties: {'neighbourhood': 'Wasleys', 'neighbourhood_group': None}

In [19]:
with open("airbnb_data/20241227_australia_sa_barossa-valley_neighbourhoods.geojson", "r", encoding="utf-8") as f:
    data = json.load(f)

features = data.get("features", [])

print(f"Liczba obiektów: {len(features)}\n")

for i, feature in enumerate(features):
    print(f"--- Obiekt #{i + 1} ---")
    
    # Właściwości (opisowe dane)
    properties = feature.get("properties", {})
    print("Właściwości:")
    for key, value in properties.items():
        print(f"  {key}: {value}")

    # Geometria (typ i liczba współrzędnych)
    geometry = feature.get("geometry", {})
    geom_type = geometry.get("type", "Brak")
    coordinates = geometry.get("coordinates", [])

    print(f"Geometria: {geom_type}")
    if geom_type == "Polygon":
        print(f"Liczba punktów (pierwszy pierścień): {len(coordinates[0])}")
    elif geom_type == "MultiPolygon":
        print(f"Liczba wielokątów: {len(coordinates)}")
        if coordinates:
            print(f"Liczba punktów w pierwszym wielokącie: {len(coordinates[0][0])}")
    print()

Liczba obiektów: 33

--- Obiekt #1 ---
Właściwości:
  neighbourhood: Wasleys
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 861

--- Obiekt #2 ---
Właściwości:
  neighbourhood: Stockwell
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 43

--- Obiekt #3 ---
Właściwości:
  neighbourhood: Penrice
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 54

--- Obiekt #4 ---
Właściwości:
  neighbourhood: Mount Crawford
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 608

--- Obiekt #5 ---
Właściwości:
  neighbourhood: Moppa
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 191

--- Obiekt #6 ---
Właściwości:
  neighbourhood: Williamstown
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 670

--- Obiekt #7 ---
Właściwości:
  neighbourhood: Moculta
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 271

--- Obiekt #8 ---
Właściwości:
  neighbourhood: Light Pass
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 41

--- Obiekt #9 ---
Właściwości:
  neighbourhood: Gawler Belt
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 55

--- Obiekt #10 ---
Właściwości:
  neighbourhood: Nuriootpa
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 72

--- Obiekt #11 ---
Właściwości:
  neighbourhood: Gawler River
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 226

--- Obiekt #12 ---
Właściwości:
  neighbourhood: Greenock
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 37

--- Obiekt #13 ---
Właściwości:
  neighbourhood: Buchfelde
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 758

--- Obiekt #14 ---
Właściwości:
  neighbourhood: Shea-Oak Log
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 214

--- Obiekt #15 ---
Właściwości:
  neighbourhood: Roseworthy
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 332

--- Obiekt #16 ---
Właściwości:
  neighbourhood: Springton
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 128

--- Obiekt #17 ---
Właściwości:
  neighbourhood: Bethany
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 212

--- Obiekt #18 ---
Właściwości:
  neighbourhood: Cockatoo Valley
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 281

--- Obiekt #19 ---
Właściwości:
  neighbourhood: Tanunda
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 397

--- Obiekt #20 ---
Właściwości:
  neighbourhood: Altona
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 258

--- Obiekt #21 ---
Właściwości:
  neighbourhood: Angaston
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 179

--- Obiekt #22 ---
Właściwości:
  neighbourhood: Concordia
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 373

--- Obiekt #23 ---
Właściwości:
  neighbourhood: Lyndoch
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 291

--- Obiekt #24 ---
Właściwości:
  neighbourhood: Ebenezer
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 178

--- Obiekt #25 ---
Właściwości:
  neighbourhood: Mount Pleasant
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 295

--- Obiekt #26 ---
Właściwości:
  neighbourhood: Eden Valley
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 111

--- Obiekt #27 ---
Właściwości:
  neighbourhood: Sandy Creek
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 264

--- Obiekt #28 ---
Właściwości:
  neighbourhood: Hewett
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 111

--- Obiekt #29 ---
Właściwości:
  neighbourhood: Flaxman Valley
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 198

--- Obiekt #30 ---
Właściwości:
  neighbourhood: Kapunda
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 700

--- Obiekt #31 ---
Właściwości:
  neighbourhood: Marananga
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 78

--- Obiekt #32 ---
Właściwości:
  neighbourhood: Freeling
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 335

--- Obiekt #33 ---
Właściwości:
  neighbourhood: Kalbeeba
  neighbourhood_group: None
Geometria: MultiPolygon
Liczba wielokątów: 1
Liczba punktów w pierwszym wielokącie: 496